version: '3'
services:
    
  client:
    build: ./client
    restart: always
    ports:
     - "3000:3000"
    expose:
      - 3000

  server:
    build: ./server
    restart: always
    ports:
     - "5000:5000"
    expose:
      - 5000
    links:
      - client